apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: tenivatt
type: Opaque
stringData:
  # из .env или вашего config.go
  DB_HOST:     "217.198.6.110"
  DB_NAME:     "tenivatt"
  DB_USER:     "tenivatt"
  DB_PASSWORD: "ZXCghoul1337228"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenivatt-config
  namespace: tenivatt
data:
  # остальные константы и параметры
  CITY:               "Краснодар"
  ANALYSIS_WINDOW_DAYS: "30"
  # и т.д.
