apiVersion: batch/v1
kind: CronJob
metadata:
  name: tenivatt-baseline
  namespace: tenivatt
spec:
  schedule: "0 1 * * *"      # в 01:00 каждый день
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: baseline
            image: registry.example.com/tenivatt:latest
            command: ["/tenivatt", "baseline"]
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: CITY
              valueFrom:
                configMapKeyRef:
                  name: tenivatt-config
                  key: CITY
            - name: ANALYSIS_WINDOW_DAYS
              valueFrom:
                configMapKeyRef:
                  name: tenivatt-config
                  key: ANALYSIS_WINDOW_DAYS
